spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/taxi?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Rathna97@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

server.port=8080
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.apache=OFF
logging.level.kafka=OFF

spring.kafka.order.bootstrap-servers=${KAFKA_RESERVATION_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.order.topic.create-order=create-order
spring.kafka.order.consumer.group-id.notification=notification
spring.kafka.order.consumer.group-id.service=service