spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/driverdb
spring.datasource.username=postgres
spring.datasource.password=12345
spring.sql.init.mode=always
spring.datasource.initialize=true
spring.sql.init.continue-on-error=true
producer
server.port=8081
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.apache=OFF
logging.level.kafka=OFF

spring.mail.host=smtp.gmail.com
spring.mail.username=katheesan2017@gmail.com
spring.mail.password=xyewdsaibxtypcva
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.kafka.order.bootstrap-servers=${KAFKA_RESERVATION_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.order.topic.create-order=create-order
spring.kafka.order.consumer.group-id.notification=create-order
spring.kafka.order.consumer.group-id.service=service