version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: taxi
      MYSQL_USER: root
      MYSQL_PASSWORD: Rathna97@
      MYSQL_ROOT_PASSWORD: Lakshani
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: 'passengerservice'
    container_name: spring-app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: taxi
      MYSQL_USER: root
      MYSQL_PASSWORD: Rathna97@
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taxi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rathna97@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_ORDER_BOOTSTRAP_SERVERS: "${KAFKA_RESERVATION_BOOTSTRAP_SERVERS:-localhost:9092}"
      SPRING_KAFKA_ORDER_TOPIC_TRIP_REQUEST: trip-request
      SPRING_KAFKA_ORDER_TOPIC_TRIP_RESPONSE: trip-response
      SPRING_KAFKA_ORDER_CONSUMER_GROUP_ID_NOTIFICATION: notification
      SPRING_KAFKA_ORDER_CONSUMER_GROUP_ID_SERVICE: service
    ports:
      - "8080:8080"

volumes:
  mysql-data:
